In [2468]:
"""Demo of List"""

# Tutorial @ https://www.datacamp.com/community/tutorials/18-most-common-python-list-questions-learn-python

# These list elements are all of the same type
zoo = ['bear', 'lion', 'panda', 'zebra']
print(zoo)

# But these list elements are not
biggerZoo = ['bear', 'lion', 'panda', 'zebra', ['chimpanzees', 'gorillas', 'orangutans', 'gibbons'], 'snake', 'giraffe']
print(biggerZoo)


['bear', 'lion', 'panda', 'zebra']
['bear', 'lion', 'panda', 'zebra', ['chimpanzees', 'gorillas', 'orangutans', 'gibbons'], 'snake', 'giraffe']


In [2469]:
# Import the `collections` library
import collections

# Check if a dictionary is hashable
print(isinstance({}, collections.Hashable))

# Check if a float is hashable
print(isinstance(0.125, collections.Hashable))

False
True


In [2470]:
# Select the first list element
oneZooAnimal = biggerZoo[0]

# Print `oneZooAnimal`
print(oneZooAnimal)

bear


In [2471]:
# Pass -1 to the index operator on biggerZoo
last_item = biggerZoo[-1]
print(last_item)

# Pass -2 to the index operator on biggerZoo
just_before_last_item = biggerZoo[-2]
print(just_before_last_item)

giraffe
snake


In [2472]:
# The Slice Notation In Lists
# Use the slice notation like this
someZooAnimals = biggerZoo[3:]

# Print to see what you exactly select from `biggerZoo`
print('biggerZoo[3:] : ', someZooAnimals)

# Try putting 2 on the other side of the colon
otherZooAnimals = biggerZoo[:5]

# Print to see what you're getting back
print('biggerZoo[:5] : ', otherZooAnimals)

# another form
print('biggerZoo[::] : ', biggerZoo[::])
print('biggerZoo[:3:] : ', biggerZoo[:3:])
print('biggerZoo[2:3:] : ', biggerZoo[2:3:])
print('biggerZoo[1:3:] : ', biggerZoo[1:3:])
print('biggerZoo[1:1:] : ', biggerZoo[1:1:])
print('biggerZoo[1:1:3] : ', biggerZoo[1:1:3])
"""In general form
# items start through the end (but the end is not included!)
a[start:end]

# items start through the rest of the array
a[start:]    

# items from the beginning through the end (but the end is not included!)
a[:end]"""


biggerZoo[3:] :  ['zebra', ['chimpanzees', 'gorillas', 'orangutans', 'gibbons'], 'snake', 'giraffe']
biggerZoo[:5] :  ['bear', 'lion', 'panda', 'zebra', ['chimpanzees', 'gorillas', 'orangutans', 'gibbons']]
biggerZoo[::] :  ['bear', 'lion', 'panda', 'zebra', ['chimpanzees', 'gorillas', 'orangutans', 'gibbons'], 'snake', 'giraffe']
biggerZoo[:3:] :  ['bear', 'lion', 'panda']
biggerZoo[2:3:] :  ['panda']
biggerZoo[1:3:] :  ['lion', 'panda']
biggerZoo[1:1:] :  []
biggerZoo[1:1:3] :  []


'In general form\n# items start through the end (but the end is not included!)\na[start:end]\n\n# items start through the rest of the array\na[start:]    \n\n# items from the beginning through the end (but the end is not included!)\na[:end]'

In [2473]:
"""start through not past end, by step
a[start:end:step]"""
# Print to see how the step value influences your result
print(biggerZoo[2::2])
print(biggerZoo[1::2])

['panda', ['chimpanzees', 'gorillas', 'orangutans', 'gibbons'], 'giraffe']
['lion', 'zebra', 'snake']


In [2474]:
# Import `choice` from the `random` library
from random import choice

# Construct your `list` variable with a list of the first 4 letters of the alphabet
list = ['a', 'b', 'c', 'd']

# Print your random 'list' element
print(choice(list))

a


In [2475]:
# Import `randrange` from the `random` library
from random import randrange

# Construct your `randomLetters` variable with a list of the first 4 letters of the alphabet
randomLetters = ['a', 'b', 'c', 'd']

# Select a random index from 'randomLetters`
randomIndex = randrange(0,len(randomLetters))

# Print your random element from `random`
print(randomLetters[randomIndex])

c


In [2476]:
"""How To Transform Python Lists Into Other Data Structures"""

# List of Strings to a String
listOfStrings = ['One', 'Two', 'Three']
strOfStrings = ''.join(listOfStrings)
print(strOfStrings)

# List Of Integers to a String
listOfNumbers = [1, 2, 3]
strOfNumbers = ''.join(str(n) for n in listOfNumbers)
print(strOfNumbers)

OneTwoThree
123


In [2477]:
# Pass your list to `tuple()`
tuple(listOfStrings)

# Transform your list into a set
set(listOfStrings)

{'One', 'Three', 'Two'}

In [2478]:
"""How To Convert Lists To A Dictionaries"""
# Convert to a dictionary
helloWorld = ['hello', 'world', '1', '2']
helloWorldDictionary = dict(zip(helloWorld[0::2], helloWorld[1::2]))
# Print out the result
print(helloWorldDictionary)

print(helloWorld[0::2])
print(helloWorld[1::2])

print('and another')
helloWorldDictionary = dict(zip(helloWorld[0::2], helloWorld[1::1]))
# Print out the result
print(helloWorldDictionary)

print(helloWorld[0::2])
print(helloWorld[1::1])

{'hello': 'world', '1': '2'}
['hello', '1']
['world', '2']
and another
{'hello': 'world', '1': '1'}
['hello', '1']
['world', '1', '2']


In [2479]:
a = [1, 2, 3, 4, 5]

# Create a list iterator object
i = iter(a)

print('i is : ', i)
# Zip and create a dictionary
print(dict(zip(i, i)))

print(len(a))

i is :  <list_iterator object at 0x10ffb1400>
{1: 2, 3: 4}
5


In [2480]:
# This is your list
list = [5, 6, 7, 8, 9]

# Check whether it's iterable
list.__iter__

<method-wrapper '__iter__' of list object at 0x10ff923c8>

In [2481]:
shortList = [1, 2, 3]
longerList = [1, 2, 3, 4, 5, 6]

# Append [4,5] to `shortList`
shortList.append([4, 5])

# Use the `print()` method to show `shortList`
print(shortList)

# Extend `longerList` with [4,5]
longerList.extend([4, 5])

# Use the `print()` method to see `longerList`
print(longerList)


[1, 2, 3, [4, 5]]
[1, 2, 3, 4, 5, 6, 4, 5]


In [2482]:
# Concatenate `shortList` with `[4,5]`
plusList = shortList + [4, 6]

#Use the `print()` method to see `plusList`
print(plusList)

[1, 2, 3, [4, 5], 4, 6]


In [2483]:
"""Sorting a list"""

rooms = [298, 397, 503, 87, 402, 503]
orders = [76, 4, 3, 5, 4]

print('before sorting', rooms)
# Use `sort()` on the `rooms` list
rooms.sort()

# Print out `rooms` to see the result
print('after sorting', rooms)

print('before sorting', orders)
# Now use the `sorted()` function on the `orders` list
sorted(orders)
# Print out orders
print('after sorting', orders)
print('after sorted(orders)', sorted(orders))


before sorting [298, 397, 503, 87, 402, 503]
after sorting [87, 298, 397, 402, 503, 503]
before sorting [76, 4, 3, 5, 4]
after sorting [76, 4, 3, 5, 4]
after sorted(orders) [3, 4, 4, 5, 76]


In [2484]:
"""Clone or Copy"""
groceries = ['beans', 'carrot', 'papaya', 'ladiesfinger']
# Copy the grocery list by slicing and store it in the `newGroceries` variable
newGroceries = groceries[:]
print('newGroceries : ', newGroceries)
# Copy the grocery list with the `list()` function and store it in a `groceriesForFriends` variable
# groceriesForFriends = list(groceries)
# Import the copy library
import copy as c

# Create a `groceriesForFamily` variable and assign the copied grocery list to it
groceriesForFamily = c.copy(groceries)
print('groceriesForFamily : ', groceriesForFamily)

# Use `deepcopy()` and assign the copied list to a `groceriesForKids` variable
groceriesForKids = c.deepcopy(groceries)
print('groceriesForKids : ', groceriesForKids)


newGroceries :  ['beans', 'carrot', 'papaya', 'ladiesfinger']
groceriesForFamily :  ['beans', 'carrot', 'papaya', 'ladiesfinger']
groceriesForKids :  ['beans', 'carrot', 'papaya', 'ladiesfinger']


In [2485]:
# This is your list
objectList = ['a', 'b', ['ab', 'ba']]

# Print out the original list to see what happened to it
print(objectList)

# Copy the `objectList`
copiedList = objectList[:]
print(copiedList)

# Change the first list element of `copiedList`
copiedList[0] = 'c'

print(copiedList)

# Go to the third element (the nested list) and change the second element
copiedList[2][1] = 'dd'

print(copiedList)


['a', 'b', ['ab', 'ba']]
['a', 'b', ['ab', 'ba']]
['c', 'b', ['ab', 'ba']]
['c', 'b', ['ab', 'dd']]


In [2486]:
"""How Does List Comprehension Work In Python?"""

[x ** 2 for x in range(10)]


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [2487]:
[x ** 2 for x in range(10) if x % 2 == 0]

[0, 4, 16, 36, 64]

In [2488]:
myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print('this is first : ', [(lambda x: x * x)(x) for x in myList])

# similarly
f = lambda x: x * x
print('this is second : ', [f(x) for x in range(10)])


this is first :  [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
this is second :  [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [2489]:
"""How To Count Occurrences Of A List Item In Python"""
print([1, 2, 9, 4, 5, 4, 1].count(4))

# Count the occurrences of the letter "a"
list = ["d", "a", "t", "a", "a", "c", "a", "m", "p"]
print('list.count("a") : ', list.count("a"))

list = ["a", "b", "b"]
print('looping : ', [[x, list.count(x)] for x in set(list)])

print(set(list))

# Import `Counter` from the `collections` library
from collections import Counter

# This is your list
list = ["a", "b", "b"]

# Pass `list` to `Counter()`
print('Counter(list) : ', Counter(list))


2
list.count("a") :  4
looping :  [['b', 2], ['a', 1]]
{'b', 'a'}
Counter(list) :  Counter({'b': 2, 'a': 1})


In [2490]:
xx = []
yy = []


def reset_values():
    """just a reset function"""
    print('reset values got called')
    xx.clear()
    yy.clear()
    xx.append([1, 2, 3, 4, 5, 6, 7, 8, 9])
    yy.append([332, 45, 67])


reset_values()
print('exploring 1')
for x in xx, yy:
    print('x is : ', x)
    # print('y is : ', yy)

reset_values()
print('exploring 2')
for x in zip(xx, yy):
    print('x is : ', x)
    # print('y is : ', yy)

reset_values()
print('exploring 3')
for x, y in zip(xx, yy):
    print('x is : ', x)
    print('y is : ', y)


reset values got called
exploring 1
x is :  [[1, 2, 3, 4, 5, 6, 7, 8, 9]]
x is :  [[332, 45, 67]]
reset values got called
exploring 2
x is :  ([1, 2, 3, 4, 5, 6, 7, 8, 9], [332, 45, 67])
reset values got called
exploring 3
x is :  [1, 2, 3, 4, 5, 6, 7, 8, 9]
y is :  [332, 45, 67]


In [2491]:
"""How To Split A Python List Into Evenly Sized Chunks"""

# Your list `x`
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Split `x` up in chunks of 3
y = zip(*[iter(x)] * 3)

# Use `list()` to print the result of `zip()`
# list(y)
# it should give O/P : [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

# Set up your list and chunk size
list = range(0, 50)
chunk = 5

# Split up your list into chunks
print('first : ', [list[i] for i in range(0, len(list), chunk)])
print('second : ', [list[i:i + chunk] for i in range(0, len(list), chunk)])
# [list[i:i + chunk] for i in range(0, len(list), chunk)]

idea = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print('idea first : ', [idea[i] for i in range(5)])
print('idea second : ', [idea[i:] for i in range(5)])
print('idea third : ', [idea[:i:] for i in range(5)])
print('idea fourth : ', [idea[:i] for i in range(5)])


first :  [0, 5, 10, 15, 20, 25, 30, 35, 40, 45]
second :  [range(0, 5), range(5, 10), range(10, 15), range(15, 20), range(20, 25), range(25, 30), range(30, 35), range(35, 40), range(40, 45), range(45, 50)]
idea first :  [0, 1, 2, 3, 4]
idea second :  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9], [3, 4, 5, 6, 7, 8, 9], [4, 5, 6, 7, 8, 9]]
idea third :  [[], [0], [0, 1], [0, 1, 2], [0, 1, 2, 3]]
idea fourth :  [[], [0], [0, 1], [0, 1, 2], [0, 1, 2, 3]]


In [2492]:
"""Looping a list"""
# This is your list
mylist = [[1, 2, 3], [4, 5, 6, 7], [8, 9, 10]]

# Loop over your list and print all elements that are of size 3
for x in mylist:
    print('x is :', x)
    if len(x) == 3:
        print('condn satisfied : ', x)

# This is your list
myList = [3, 4, 5, 6]

# Loop over `myList` and print tuples of all indices and values 
for i, val in enumerate(myList):
    print('loc %d, value is %d' % (i, val))


x is : [1, 2, 3]
condn satisfied :  [1, 2, 3]
x is : [4, 5, 6, 7]
x is : [8, 9, 10]
condn satisfied :  [8, 9, 10]
loc 0, value is 3
loc 1, value is 4
loc 2, value is 5
loc 3, value is 6


In [2493]:
"""Flatten your lists"""

# Your initial list of lists
list = [[1, 2], [3, 4], [5, 6]]

# Flatten out your original list of lists with `sum()`
sum(list, [])


[1, 2, 3, 4, 5, 6]

In [2494]:
"""Using Numypy instead of Lists"""

import numpy

arry = numpy.array([])
print(arry)

# Make a NumPy array of four rows and two columns and filled with 0
print('first ', numpy.zeros(shape=(4, 3)))

# Make a NumPy array of 1 values of three columns
print('second ', numpy.ones(3))

# Make an empty NumPy array
print('third ', numpy.empty(shape=(0, 0)))


[]
first  [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
second  [ 1.  1.  1.]
third  []


In [2495]:
cost = [0.424, 0.4221, 0.4185, 0.4132, 0.413]
cases = [10, 20, 30, 40, 50]

for c in range(len(cost)):
    cost[c] = (cost[c] * cases[c] / sum(cases))
print('before : ', cost)
cost = sum(cost)
print('after sum : ', cost)

before :  [0.02826666666666667, 0.056280000000000004, 0.0837, 0.11018666666666665, 0.13766666666666666]
after sum :  0.41609999999999997


In [2496]:
# Import numpy as np
import numpy as np

# Make a NumPy array
a = np.array([1, 2, 3, 4, 5])

# Return the 50th percentile of our NumPy array
p = np.percentile(a, 75)

#Print the result
print(p)


4.0


In [2497]:
"""Sum List Element-wise"""
list1 = [1, 2, 3]
list2 = [4, 5, 6]

from operator import add

print('val : ', map(add, list1, list2))

print('first : ', [sum(x) for x in zip(list1, list2)])
print('second : ', [x for x in zip(list1, list2)])


val :  <map object at 0x11004a470>
first :  [5, 7, 9]
second :  [(1, 4), (2, 5), (3, 6)]


In [2498]:
# Import numpy as np
import numpy as np

# Make your lists into NumPy arrays
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Element-wise addition
sum_vector = vector1 + vector2 

# Print the result
print(sum_vector)

[5 7 9]
